// Your personal week schedule templates
// Edit this file to customize your weekly schedules
// This file is kept in git for your personal setup

export const WEEK_TEMPLATES = {
  normal: {
    Mon: [
      "workout",
      "depth",
      "depth",
      "coding",
      "stories",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Tue: [
      "workout",
      "coding",
      "depth",
      "depth",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "flex",
      "stretch-flex",
      "blocked",
      "blocked",
      "review",
      "blocked",
      "free",
    ],
    Wed: [
      "workout",
      "coding",
      "depth",
      "stories",
      "blocked",
      "project",
      "project",
      "stretch-project",
      "flex",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Thu: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Fri: [
      "workout",
      "stories",
      "coding",
      "depth",
      "project",
      "stretch-project",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Sat: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Sun: [
      "stretch-coding",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
  },
  travel: {
    Mon: [
      "workout",
      "coding",
      "review",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Tue: [
      "workout",
      "depth",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Wed: [
      "workout",
      "stories",
      "coding",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Thu: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Fri: [
      "workout",
      "coding",
      "depth",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Sat: [
      "review",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
    Sun: [
      "review",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "free",
    ],
  },
  hard: {
    Mon: [
      "workout",
      "depth",
      "coding",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Tue: [
      "workout",
      "coding",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "free",
      "free",
      "blocked",
      "blocked",
      "review",
      "blocked",
      "free",
    ],
    Wed: [
      "workout",
      "depth",
      "free",
      "blocked",
      "blocked",
      "project",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Thu: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Fri: [
      "workout",
      "stories",
      "coding",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Sat: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
    Sun: [
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "free",
      "blocked",
      "blocked",
      "blocked",
      "review",
      "free",
      "free",
    ],
  },
};

export const MODE_NOTES = {
  normal: "Normal week: core blocks committed, stretch blocks (dotted) are optional upgrades.",
  travel: "Travel week: stripped to essentials only. No stretch blocks. Focus on coding and one depth topic.",
  hard: "Hard week: all stretch blocks removed. Core commitments only. Protect workout and one coding session — momentum matters.",
};

// Weekly progress goals (vary by week type) - customize these for your own targets
export const WEEKLY_GOALS = {
  normal: [
    { key: "leetcode", label: "LeetCode problems", goal: 3, color: "#534AB7" },
    { key: "depth", label: "Tech depth sessions", goal: 2, color: "#0F6E56" },
    { key: "project", label: "Pet project hours", goal: 3, color: "#854F0B" },
    { key: "stories", label: "Interview stories written", goal: 2, color: "#993C1D" },
    { key: "apps", label: "Applications sent", goal: 3, color: "#185FA5" },
  ],
  travel: [
    { key: "leetcode", label: "LeetCode problems", goal: 1, color: "#534AB7" },
    { key: "depth", label: "Tech depth sessions", goal: 1, color: "#0F6E56" },
    { key: "project", label: "Pet project hours", goal: 1, color: "#854F0B" },
    { key: "stories", label: "Interview stories written", goal: 0, color: "#993C1D" },
    { key: "apps", label: "Applications sent", goal: 1, color: "#185FA5" },
  ],
  hard: [
    { key: "leetcode", label: "LeetCode problems", goal: 2, color: "#534AB7" },
    { key: "depth", label: "Tech depth sessions", goal: 1, color: "#0F6E56" },
    { key: "project", label: "Pet project hours", goal: 1, color: "#854F0B" },
    { key: "stories", label: "Interview stories written", goal: 1, color: "#993C1D" },
    { key: "apps", label: "Applications sent", goal: 1, color: "#185FA5" },
  ],
};

// Core hours progress bar settings
export const PROGRESS_SETTINGS = {
  coreHoursMax: 20, // Max hours for progress bar (adjust based on your schedule)
  cumulativeGoal: 30, // Target for cumulative totals progress bar
};

// Default kanban tasks
export const KANBAN_TASKS = [
  { id: 1, col: 0, title: "NeetCode: Arrays & Hashing", tag: "coding", note: "Start here. 5 problems." },
  { id: 2, col: 0, title: "NeetCode: Sliding Window", tag: "coding", note: "Contiguous array — your gap." },
  { id: 3, col: 0, title: "NeetCode: Two Pointers", tag: "coding", note: "" },
  { id: 4, col: 0, title: "Live coding (recorded)", tag: "coding", note: "Narrate out loud. Even to yourself." },
  { id: 5, col: 0, title: "Tech depth: Frontend perf", tag: "depth", note: "CWV, bundle opt, rendering" },
  { id: 6, col: 0, title: "Tech depth: DB optimization", tag: "depth", note: "Indexing, N+1, query planning" },
  { id: 7, col: 0, title: "Tech depth: Security (OWASP)", tag: "depth", note: "Auth patterns, XSS/CSRF" },
  { id: 8, col: 0, title: "Tech depth: Architecture tradeoffs", tag: "depth", note: "CAP theorem, micro vs mono" },
  { id: 9, col: 0, title: "Story mining (5 projects)", tag: "interview", note: "Scale, decisions, tradeoffs, results" },
  { id: 10, col: 0, title: "STAR bank (10 questions)", tag: "interview", note: "Leadership, conflict, failure, scale" },
  { id: 11, col: 0, title: "Pick pet project", tag: "project", note: "LLM/agentic preferred" },
  { id: 12, col: 0, title: "Pet project: ship v0.1", tag: "project", note: "" },
  { id: 13, col: 0, title: "Pet project: ship v0.2", tag: "project", note: "" },
  { id: 14, col: 0, title: "Freeze protocol (write on card)", tag: "mindset", note: '"Brute force first, narrate always"' },
];

// Default wins (empty initially, user fills these in)
export const DEFAULT_WINS = [];
